# Generated by Django 2.0.6 on 2018-08-27 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('happened', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
            ],
            options={
                'verbose_name_plural': 'Действия',
                'verbose_name': 'Действие',
            },
        ),
        migrations.CreateModel(
            name='UserActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('char_id', models.CharField(max_length=32, unique=True, verbose_name='Идентификатор (символьный)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Типы действий',
                'verbose_name': 'Тип действия',
            },
        ),
        migrations.CreateModel(
            name='VKAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('aid', models.CharField(max_length=255, verbose_name='Айди')),
                ('fname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('photo', models.CharField(max_length=255, verbose_name='Изображение')),
                ('num_messages', models.IntegerField(verbose_name='Количество отправленных сообщений при рассылке')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользоваватель')),
            ],
            options={
                'verbose_name_plural': 'Аккаунты вк',
                'verbose_name': 'Аккаунт вк',
            },
        ),
        migrations.CreateModel(
            name='VKApiApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, unique=True, verbose_name='Айди приложения')),
            ],
            options={
                'verbose_name_plural': 'Приложения',
                'verbose_name': 'Приложение',
            },
        ),
        migrations.CreateModel(
            name='VKClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='Айди')),
                ('fname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('photo', models.CharField(max_length=255, verbose_name='Фото')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбран')),
                ('spammed', models.BooleanField(default=False, verbose_name='Разослано?')),
                ('visited', models.BooleanField(default=False, verbose_name='Просмотрен')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='VKComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='Айди пользователя')),
                ('fname', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('lname', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('photo', models.CharField(max_length=255, verbose_name='Фото пользователя')),
                ('text', models.TextField(default='', verbose_name='Текст комментария')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбран')),
                ('visited', models.BooleanField(default=False, verbose_name='Просмотрен')),
                ('spammed', models.BooleanField(default=False, verbose_name='Разослано?')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'verbose_name': 'Комментарий',
            },
        ),
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, verbose_name='Айди')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.CharField(max_length=255, verbose_name='Картинка')),
                ('num_members', models.IntegerField(verbose_name='Количество участников')),
                ('members_ids', models.TextField(default='', verbose_name='Список айдишников')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Источники',
                'verbose_name': 'Источник',
            },
        ),
        migrations.CreateModel(
            name='VKSpamDialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_uid', models.CharField(max_length=255, verbose_name='Айди собеседника')),
                ('with_fname', models.CharField(max_length=255, verbose_name='Имя собеседника')),
                ('with_lname', models.CharField(max_length=255, verbose_name='Фамилия собеседника')),
                ('with_photo', models.CharField(max_length=255, verbose_name='Изображение собеседника')),
                ('num_messages', models.IntegerField(verbose_name='Количество сообщений')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользоваватель')),
                ('vk_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.VKAccount', verbose_name='Аккаунт вк')),
            ],
            options={
                'verbose_name_plural': 'Диалоги',
                'verbose_name': 'Диалог',
            },
        ),
        migrations.CreateModel(
            name='VKSpamDialogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_vk_account', models.BooleanField(verbose_name='От аккаунта вк?')),
                ('message_id', models.CharField(max_length=255, verbose_name='Айди сообщения')),
                ('body', models.TextField(verbose_name='Тело сообщения')),
                ('sent_at', models.DateTimeField(verbose_name='Время отправки')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.VKSpamDialog', verbose_name='Диалог')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользоваватель')),
            ],
            options={
                'verbose_name_plural': 'Сообщения',
                'verbose_name': 'Сообщение',
            },
        ),
        migrations.CreateModel(
            name='VKToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Токен')),
                ('active', models.BooleanField(default=True, verbose_name='Рабочий')),
            ],
            options={
                'verbose_name_plural': 'Токены',
                'verbose_name': 'Токен',
            },
        ),
        migrations.AddField(
            model_name='vkcomment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.VKGroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='vkcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользоваватель'),
        ),
        migrations.AddField(
            model_name='vkclient',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.VKGroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='vkclient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.UserActionType', verbose_name='Тип действия'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
