# Generated by Django 2.0.3 on 2019-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждённая почта'),
        ),
        migrations.AlterField(
            model_name='userspamtext',
            name='spam_text',
            field=models.TextField(default='Здравствуйте, <имя> <фамилия>!\nИнтересуетесь группой <группа>?\nТогда вам понравится...', verbose_name='Текст рассылки сообщений'),
        ),
    ]
